package com.saifurtech.locale.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

import java.util.List;

@Data
@ToString
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "ZipCodesByCountryCityAndState")
@DynamoDBDocument
public class ZipCodesByCountryCityAndState {

    @JsonProperty("country")
    @DynamoDBAttribute
    private String country;

    @JsonProperty("city")
    @DynamoDBAttribute
    @DynamoDBHashKey(attributeName = "city")
    private String city;

    @JsonProperty("state")
    @DynamoDBAttribute
    private String state;

    @JsonProperty("results")
    @DynamoDBAttribute
    private List<String> allZipCodes;

    @DynamoDBAutoGeneratedKey
    @JsonIgnore
    private String id;

}
